### ISSUE TITLE
"Reach the college" page design

### ISSUE THREAD

**Issue by deprov447** [deprov447/cse-fresher-website#11]
There is a map API which has to be integrated.
@yasht01 please share the details, if anyone else want to help

**Comment by deprov447** [comment]
Anyone else can also contribute

**Comment by yasht01** [comment]
Yeah, so we are using MapBox GL JS for map rendering. Checkout their docs if anyone is interested. I am starting today so, we can contribute together.
[Mapbox](https://www.mapbox.com/)
[Mapbox API](https://docs.mapbox.com/mapbox-gl-js/api/)
