### ISSUE TITLE
Theme toggler 

### ISSUE THREAD

**Issue by sagar-barapatre** [deprov447/cse-fresher-website#15]
[Click Here for more ideas](https://codepen.io/search/pens?q=dark+mode)

I think [this](https://codepen.io/lerida/pen/ZEbWBjp) is good. What say??

**Comment by Sandeepan-Das** [comment]
Yes it's looking nice.

**Comment by deprov447** [comment]
Its looking awesome. But since the Front-End is still in initial development stage shouldn't we keep this at hold for sometime? It would be easier to implement once the frontend is ready. @sagar-barapatre thoughts?

**Comment by sagar-barapatre** [comment]
> Its looking awesome. But since the Front-End is still in initial development stage shouldn't we keep this at hold for sometime? It would be easier to implement once the frontend is ready. @sagar-barapatre thoughts?

Yeah !! I am not asking to implement it now, I was just telling that we could add this on our website.✌️

**Comment by yasht01** [comment]
[This one](https://codepen.io/demilad/pen/bZRjpb) is good too.

**Comment by sagar-barapatre** [comment]
Jo bologe woh kr lenge...

**Comment by deprov447** [comment]
@sagar-barapatre I think this is quite a good stage to implement this feature.. @sagar-barapatre You wanna start working on this?

**Comment by sagar-barapatre** [comment]
I am busy in some other work. So you guys may take up this task. 
Or else I can do it, but it might take a little while.

**Comment by deprov447** [comment]
Okay... This isn't very necessary as of now. So if you want you can try completing this by next week, or else close the issue
