### ISSUE TITLE
Navbar toggle button not available on mobile

### ISSUE THREAD

**Issue by deprov447** [deprov447/cse-fresher-website#31]
## Issue
Navbar toggle button is not visible after opening the sidenav on mobile display.

## Idea
One way of fixing this is by adding a toggle button replica to sidenav itself....
Other suggestions are also welcomed

**Comment by yasht01** [comment]
Is there a way to extend the navbar to only 80% of the mobile screen? Then, the navbar toggle button will be visible after opening the navbar.
