### ISSUE TITLE
Headings overlapping with nav-button

### ISSUE THREAD

**Issue by deprov447** [deprov447/cse-fresher-website#55]
On Mobile/Tablet views the heading of the pages are sometimes overlapping with the nav button.

This is an easy fix. One can just replace the font size of headings for 'px' with some responsive unit like 'rem' or '%' or something.

![image](https://user-images.githubusercontent.com/57551996/100495639-6e82d480-3173-11eb-81ef-64f6e652a200.png)

**Comment by yasht01** [comment]
@deprov447 Should I work for this issue on master branch or help-us-know-you branch?
