### ISSUE TITLE
Navbar not fixed to the top in desktop site

### ISSUE THREAD

**Issue by yasht01** [deprov447/cse-fresher-website#60]
![081a1f997397dc032f527068974e7777](https://user-images.githubusercontent.com/55907631/101372836-511bdc00-38d2-11eb-92e9-e9c5e8a6fdb1.gif)

**Comment by deprov447** [comment]
Actually that's quite a very good suggestion. This will enhance UX quite much. The only problem I see is on gallery page. (something else can be done there, suggestions??)

**Comment by yasht01** [comment]
I think keeping the navbar visible during scrolling the gallery section does not affect UX much. If possible, the navbar can change color(opposite in contrast to the image, i.e white) while scrolling the gallery section.
